# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform Traefik certs dumper installation tasks
  block:
    - name: Validate Traefik certs dumper configuration
      when: traefik_certs_dumper_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Traefik certs dumper
      when: traefik_certs_dumper_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-traefik-certs-dumper
    - install-all
    - install-traefik-certs-dumper

- name: Perform Traefik certs dumper uninstallation tasks
  block:
    - name: Uninstall Traefik certs dumper
      when: not traefik_certs_dumper_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-traefik-certs-dumper
